all:pipeline.c sequence.c
	gcc pipeline.c -std=c99 -Wall -o pipeline
	gcc sequence.c -std=c99 -Wall -o sequence
pipeline: pipeline.c
	gcc pipeline.c -std=c99 -Wall -o pipeline
sequence: sequence.c
	gcc sequence.c -std=c99 -Wall -o sequence
